### ISSUE TITLE
java.util.concurrent.TimeoutException: android.media.MediaMuxer.finalize() timed out after 10 seconds

### ISSUE THREAD

**Issue by jp1017** [saki4510t/UVCCamera#115]
Record per 10 minutes error of Test4: 

```
java.util.concurrent.TimeoutException: android.media.MediaMuxer.finalize() timed out after 10 seconds
at android.media.MediaMuxer.nativeRelease(Native Method)
at android.media.MediaMuxer.finalize(MediaMuxer.java:240)
at java.lang.Daemons$FinalizerDaemon.doFinalize(Daemons.java:187)
at java.lang.Daemons$FinalizerDaemon.run(Daemons.java:170)
at java.lang.Thread.run(Thread.java:841)
```

**Comment by saki4510t** [comment]
Hi,

I assume this seems MediaMuxer took too long time to write muxed data.
What device do you use? As I know HUAWEI devices sometimes have issue on MediaCodec/MediaMuxer.

Or if your primary storage physically exists on SD card, writing speed of the card may be slow than required. Please try to use faster one.

**Comment by jp1017** [comment]
Hi, @saki4510t 

It's our own device, CPU info here: 

![2](https://cloud.githubusercontent.com/assets/7868514/23165390/da10e42e-f876-11e6-959a-ed0b0d661fb3.png)

May be this reason? CPU? :smile:
