### ISSUE TITLE
surfaceTexture becomes null when closing activity and reopening it

### ISSUE THREAD

**Issue by miggymamba** [saki4510t/UVCCamera#176]
Hi,

I tried implementing the detection of the usb device automatically. It works the first time the activity is opened, and the it goes on the `onConnect` callback in the `OnDeviceConnectListener`. However, it crashes on the `startPreview` method, saying the surfaceTexture must not be null. Any ideas on how to fix this? 

`java.lang.IllegalArgumentException: surfaceTexture must not be null
                                                       at android.view.Surface.<init>(Surface.java:140)
                                                       at digital.binary.zesto.MainActivity.startPreview(MainActivity.java:248)
                                                       at digital.binary.zesto.MainActivity.access$800(MainActivity.java:27)
                                                       at digital.binary.zesto.MainActivity$6.onConnect(MainActivity.java:267)
                                                       at com.serenegiant.usb.USBMonitor$3.run(USBMonitor.java:570)
                                                       at android.os.Handler.handleCallback(Handler.java:739)
                                                       at android.os.Handler.dispatchMessage(Handler.java:95)
                                                       at android.os.Looper.loop(Looper.java:168)
                                                       at android.os.HandlerThread.run(HandlerThread.java:61)

Line 248 is this -> `mCameraHandler.startPreview(new Surface(st));`
Line 27 is the class declaration -> `public final class MainActivity extends BaseActivity implements CameraDialog.CameraDialogParent`
Line 267 is this -> `startPreview();`
Line 570 is this -> `mOnDeviceConnectListener.onConnect(device, ctrlBlock, createNew);`

Any ideas on why it is crashing? I checked the Log of the activity lifecycle and each one is being called. Don't know why the surface texture is null. Thanks!

**Comment by ldima** [comment]
You should know what surface and surface texture is available for that use isAvailable()
