### ISSUE TITLE
Problem on the newest Samsung firmwares

### ISSUE THREAD

**Issue by ThomasCZ** [saki4510t/UVCCamera#177]
Looks like, problem is caused by Linux SE - enforcing. Same on Samsung Galaxy Tab 4, Galaxy S6, S7

`E/audit: type=1400 audit(1496405784.861:1953): avc:  denied  { create } for  pid=26566 comm="serenegiant" scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:r:untrusted_app:s0:c512,c768 tclass=netlink_kobject_uevent_socket permissive=0 SEPF_SECMOBILE_7.0_0004`

```
06-02 11:21:35.704 13726-13748/? I/libusb/core: [13748*core.c:2085:libusb_init2]:libusb v1.0.19.10903
06-02 11:21:35.704 13726-13748/? I/libusb/usbfs: [13748*android_usbfs.c:504:op_init2]:start up hotplug event handler
06-02 11:21:35.704 13726-13748/? I/libusb/usbfs: [13748*android_usbfs.c:512:op_init2]:call android_scan_devices
06-02 11:21:35.704 13726-13748/? E/UVCCamera: [13748*UVCCamera.cpp:172:connect]:could not open camera:err=-1
06-02 11:21:35.704 13726-13748/? E/AndroidRuntime: FATAL EXCEPTION: BaseActivity
                                                   Process: com.serenegiant.usbcameratest0, PID: 13726
                                                   java.lang.UnsupportedOperationException: open failed:result=-1
                                                       at com.serenegiant.usb.UVCCamera.open(UVCCamera.java:204)
                                                       at com.serenegiant.usbcameratest0.MainActivity$2$1.run(MainActivity.java:149)
```

**Comment by arpu** [comment]
have the same problem on moto g android 5.1
06-09 01:00:52.878 29254-29254/? W/sh: type=1400 audit(0.0:812): avc: denied { ioctl } for uid=2000 path="socket:[1793568]" dev="sockfs" ino=1793568 scontext=u:r:shell:s0 tcontext=u:r:adbd:s0 tclass=unix_stream_socket permissive=0

any idea how to solve this?
