### ISSUE TITLE
FATAL EXCEPTION

### ISSUE THREAD

**Issue by dalwadi2** [saki4510t/UVCCamera#198]
The app is working completely fine before, I Don't know now its stop working and giving me this type of error.
```


FATAL EXCEPTION: UVCCameraCapturer
                                                              Process: com.twilio.video.examples.uvccameracapturer, PID: 23779
                                                              java.lang.UnsupportedOperationException: open failed:result=-1
                                                                  at com.serenegiant.usb.UVCCamera.open(UVCCamera.java:204)
                                                                  at com.twilio.video.examples.uvccameracapturer.UVCCameraCapturer.startUvcCameraPreviewOnCameraThread(UVCCameraCapturer.java:198)
                                                                  at com.twilio.video.examples.uvccameracapturer.UVCCameraCapturer.access$500(UVCCameraCapturer.java:30)
                                                                  at com.twilio.video.examples.uvccameracapturer.UVCCameraCapturer$2$2.run(UVCCameraCapturer.java:85)
                                                                  at android.os.Handler.handleCallback(Handler.java:751)
                                                                  at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                  at android.os.Looper.loop(Looper.java:154)
                                                                  at android.os.HandlerThread.run(HandlerThread.java:61)
```
Can you help me to find out the solution.?

**Comment by sappho192** [comment]
Which NDK version are you using? If it's 15, try 14b.

**Comment by dalwadi2** [comment]
okay, i'll try your suggestion.
if it will succeed, I'll close the issue.
thanks @sappho192

**Comment by dalwadi2** [comment]
yes, it's working on 14b @sappho192 .
can you Explain what was the issue with updated NDK?

**Comment by sappho192** [comment]
This issue is in same context of Issue #181 .
Don't know what the problem exactly is, but it seems that Linux system call related stuff in NDK 15 have some matter. Maybe next release of NDK will solve this but not sure...

**Comment by dalwadi2** [comment]
okay, thanks @sappho192

**Comment by sappho192** [comment]
Please close this issue since it's solved :)

**Comment by dalwadi2** [comment]
already I closed it @sappho192
