### ISSUE TITLE
Sometimes app crashes on opening with following error

### ISSUE THREAD

**Issue by v4-adi** [saki4510t/UVCCamera#255]
[FATAL EXCEPTION: RenderThread
                                                                                      Process: test.cloudsethtest.com.twiliouvctest, PID: 13827
                                                                                      java.lang.IllegalArgumentException: java.lang.RuntimeException: createWindowSurface failed error=12291
                                                                                          at com.serenegiant.glutils.EGLBase14.createWindowSurface(EGLBase14.java:466)
                                                                                          at com.serenegiant.glutils.EGLBase14.access$100(EGLBase14.java:44)
                                                                                          at com.serenegiant.glutils.EGLBase14$EglSurface.<init>(EGLBase14.java:90)
                                                                                          at com.serenegiant.glutils.EGLBase14$EglSurface.<init>(EGLBase14.java:79)
                                                                                          at com.serenegiant.glutils.EGLBase14.createFromSurface(EGLBase14.java:192)
                                                                                          at com.serenegiant.glutils.EGLBase14.createFromSurface(EGLBase14.java:43)
                                                                                          at com.serenegiant.usb.widget.UVCCameraTextureView$RenderHandler$RenderThread.init(UVCCameraTextureView.java:564)
                                                                                          at com.serenegiant.usb.widget.UVCCameraTextureView$RenderHandler$RenderThread.run(UVCCameraTextureView.java:543)
                                                                                       Caused by: java.lang.RuntimeException: createWindowSurface failed error=12291
                                                                                          at com.serenegiant.glutils.EGLBase14.createWindowSurface(EGLBase14.java:460)
                                                                                          at com.serenegiant.glutils.EGLBase14.access$100(EGLBase14.java:44) 
                                                                                          at com.serenegiant.glutils.EGLBase14$EglSurface.<init>(EGLBase14.java:90) 
                                                                                          at com.serenegiant.glutils.EGLBase14$EglSurface.<init>(EGLBase14.java:79) 
                                                                                          at com.serenegiant.glutils.EGLBase14.createFromSurface(EGLBase14.java:192) 
                                                                                          at com.serenegiant.glutils.EGLBase14.createFromSurface(EGLBase14.java:43) 
                                                                                          at com.serenegiant.usb.widget.UVCCameraTextureView$RenderHandler$RenderThread.init(UVCCameraTextureView.java:564) 
                                                                                          at com.serenegiant.usb.widget.UVCCameraTextureView$RenderHandler$RenderThread.run(UVCCameraTextureView.java:543) ](url)

**Comment by v4-adi** [comment]
@saki4510t
