### ISSUE TITLE
Unable to run the demos provided

### ISSUE THREAD

**Issue by pramodgobburi** [saki4510t/UVCCamera#276]
Hello,

I recently downloaded this project and am trying to run the demo projects on my Samsung Galaxy s8, when I launch the app the usb camera is recognized but it fails to show the preview or crashes after I tap "Ok". Posted below is the error from log cat.

PS: I am using a Logitech C920 pro webcam.

 Please help.

Error
--------- beginning of crash
11-26 11:28:30.909 17969 17986 E AndroidRuntime: FATAL EXCEPTION: BaseActivity
11-26 11:28:30.909 17969 17986 E AndroidRuntime: Process: com.serenegiant.usbcameratest, PID: 17969
11-26 11:28:30.909 17969 17986 E AndroidRuntime: java.lang.UnsupportedOperationException: open failed:result=-1
11-26 11:28:30.909 17969 17986 E AndroidRuntime:        at com.serenegiant.usb.UVCCamera.open(UVCCamera.java:204)
11-26 11:28:30.909 17969 17986 E AndroidRuntime:        at com.serenegiant.usbcameratest.MainActivity$2$1.run(MainActivity.java:142)
11-26 11:28:30.909 17969 17986 E AndroidRuntime:        at android.os.Handler.handleCallback(Handler.java:751)
11-26 11:28:30.909 17969 17986 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:95)
11-26 11:28:30.909 17969 17986 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:154)
11-26 11:28:30.909 17969 17986 E AndroidRuntime:        at android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by jehrlatgoogle** [comment]
same issue with Logitech C930e. I am wondering what is different in the underlying library between these samples and this app, which is apparently also from com.serenigiant:
https://www.apkmonk.com/app/com.serenegiant.usbwebcamera/
The latter works just fine
