### ISSUE TITLE
UnsupportedOperationException: open failed:result=-1          

### ISSUE THREAD

**Issue by apples398** [saki4510t/UVCCamera#296]
Process: com.serenegiant.usbcameratest, PID: 5575
                                                 java.lang.UnsupportedOperationException: open failed:result=-1
                                                     at com.serenegiant.usb.UVCCamera.open(UVCCamera.java:204)
                                                     at com.serenegiant.usbcameratest.MainActivity$2$1.run(MainActivity.java:142)
                                                     at android.os.Handler.handleCallback(Handler.java:739)
                                                     at android.os.Handler.dispatchMessage(Handler.java:95)
                                                     at android.os.Looper.loop(Looper.java:135)
                                                     at android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by apples398** [comment]
Process: com.serenegiant.usbcameratest, PID: 1736
                                                 java.lang.UnsupportedOperationException: open failed:result=-50
                                                     at com.serenegiant.usb.UVCCamera.open(UVCCamera.java:204)

**Comment by lohithn4** [comment]
me too facing same issue

**Comment by lohithn4** [comment]
[https://github.com/saki4510t/UVCCamera/issues/275](url)
fixed the issue for me

**Comment by apples398** [comment]
Thanks。

**Comment by yeshiyuan00** [comment]
page not found 404

**Comment by CreazyBlade** [comment]
page not found 404

**Comment by RaimuYeh** [comment]
> page not found 404

The link is not correctly
