### ISSUE TITLE
FATAL EXCEPTION: USBMonitor UsbDeviceConnection null

### ISSUE THREAD

**Issue by agonza1** [saki4510t/UVCCamera#315]
Android 7 (Nougat) failing with the following error:

`FATAL EXCEPTION: USBMonitor
                                                                                Process: com.serenegiant.usbcameratest8, PID: 16626
                                                                                java.lang.NullPointerException: Attempt to invoke virtual method 'byte[] android.hardware.usb.UsbDeviceConnection.getRawDescriptors()' on a null object reference
                                                                                    at com.serenegiant.usb.USBMonitor.updateDeviceInfo(USBMonitor.java:938)
                                                                                    at com.serenegiant.usb.USBMonitor$UsbControlBlock.<init>(USBMonitor.java:1013)
                                                                                    at com.serenegiant.usb.USBMonitor$UsbControlBlock.<init>(USBMonitor.java:0)
                                                                                    at com.serenegiant.usb.USBMonitor$3.run(USBMonitor.java:601)
                                                                                    at android.os.Handler.handleCallback(Handler.java:751)
                                                                                    at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                    at android.os.Looper.loop(Looper.java:154)
                                                                                    at android.os.HandlerThread.run(HandlerThread.java:61)`

Seems that manager.openDevice(device) returns null

**Comment by ericlee1994** [comment]
I have the same problem，especially when insert the USB camera. And i think i have unregisted the camera already.
