### ISSUE TITLE
 Failed to open libwvm.so: dlopen failed: library "libstlport.so" not found

### ISSUE THREAD

**Issue by fuliteng** [saki4510t/UVCCamera#382]
06-29 14:44:44.070 5295-5365/com.serenegiant.usbcameratest4:uvcservice E/WVMExtractor: Failed to open libwvm.so: dlopen failed: library "libstlport.so" not found
06-29 14:44:44.316 5295-5366/com.serenegiant.usbcameratest4:uvcservice E/libuvc/device: [5366*device.c:944:uvc_scan_control]:UVC_ERROR_INVALID_DEVICE
06-29 14:44:44.316 5295-5366/com.serenegiant.usbcameratest4:uvcservice E/UVCCamera: [5366*UVCCamera.cpp:172:connect]:could not open camera:err=-50
    
    --------- beginning of crash
06-29 14:44:44.319 5295-5366/com.serenegiant.usbcameratest4:uvcservice E/AndroidRuntime: FATAL EXCEPTION: CameraThread
    Process: com.serenegiant.usbcameratest4:uvcservice, PID: 5295
    Theme: themes:{}
    java.lang.UnsupportedOperationException: open failed:result=-50
        at com.serenegiant.usb.UVCCamera.open(UVCCamera.java:207)
        at com.serenegiant.service.CameraServer$CameraThread.handleOpen(CameraServer.java:379)
        at com.serenegiant.service.CameraServer.handleMessage(CameraServer.java:262)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:148)
        at com.serenegiant.service.CameraServer$CameraThread.run(CameraServer.java:632)
06-29 14:44:44.388 973-2853/? E/[EGL-ERROR]: EGLBoolean __egl_platform_create_surface_window(egl_surface*, mali_base_ctx_handle):933: =========> usage 0x900
06-29 14:44:45.031 5295-5368/com.serenegiant.usbcameratest4:uvcservice E/[EGL-ERROR]: EGLBoolean __egl_platform_create_surface_window(egl_surface*, mali_base_ctx_handle):933: =========> usage 0x100
06-29 14:44:45.053 5295-5368/com.serenegiant.usbcameratest4:uvcservice E/[EGL-ERROR]: EGLBoolean __egl_platform_create_surface_window(egl_surface*, mali_base_ctx_handle):933: =========> usage 0x900

**Comment by shekharartemedia** [comment]
Failed to open libwvm.so: dlopen failed: library "libwvm.so" not found. i am getting this issue on lava phone when i open the gallery from my app.
