### ISSUE TITLE
E/CameraClientThread: select: / Error on Android 9

### ISSUE THREAD

**Issue by ghost** [saki4510t/UVCCamera#457]
Hi, I use usbCameraTest4 with rename project and now using well.

I also tried with Android 9 but faced with error again.
Lower android version is working well of course.
I tested with  #454  and #443(change api 26 to 28) but occurred same error.

Below is my log

03-28 12:37:03.117 21371-21371/com.test.rDown W/ActivityThread: handleWindowVisibility: no activity for token android.os.BinderProxy@fb1bc75
03-28 12:37:03.183 21371-21371/com.test.rDown I/DecorView: createDecorCaptionView >> DecorView@49a66d6[], isFloating: false, isApplication: true, hasWindowDecorCaption: false, hasWindowControllerCallback: true
03-28 12:37:03.213 21371-21371/com.test.rDown V/CameraFragment: Constructor:
03-28 12:37:03.214 21371-21371/com.test.rDown V/CameraFragment: onAttach:
03-28 12:37:03.217 21371-21371/com.test.rDown V/CameraFragment: onCreate:
03-28 12:37:03.217 21371-21371/com.test.rDown V/Monitor null: create monitor
03-28 12:37:03.219 21371-21371/com.test.rDown V/CameraFragment: onCreateView:
03-28 12:37:03.261 21371-21371/com.test.rDown V/CameraFragment: onResume:
03-28 12:37:03.261 21371-21371/com.test.rDown V/Connection Step: or this?
03-28 12:37:03.277 21371-21371/com.test.rDown D/InputTransport: Input channel constructed: fd=81
03-28 12:37:03.277 21371-21371/com.test.rDown D/ViewRootImpl@e9581c5[MainActivity]: setView = DecorView@49a66d6[MainActivity] TM=true MM=false
03-28 12:37:03.287 21371-21371/com.test.rDown D/SurfaceView: onWindowVisibilityChanged(0) true android.view.SurfaceView{7e8d24b VFE...C.. ......I. 0,0-0,0 #7f08002b app:id/camera_view_sub} of ViewRootImpl@e9581c5[MainActivity]
03-28 12:37:03.288 21371-21371/com.test.rDown D/ViewRootImpl@e9581c5[MainActivity]: dispatchAttachedToWindow
03-28 12:37:03.314 21371-21371/com.test.rDown D/ViewRootImpl@e9581c5[MainActivity]: Relayout returned: old=[0,0][1080,2220] new=[0,0][1080,2220] result=0x7 surface={valid=true 3400005632} changed=true
03-28 12:37:03.317 21371-21394/com.test.rDown D/mali_winsys: EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, EGLBoolean) returns 0x3000
03-28 12:37:03.317 21371-21394/com.test.rDown D/OpenGLRenderer: eglCreateWindowSurface = 0xde63cfc0, 0xcaa7f808
03-28 12:37:03.331 21371-21371/com.test.rDown D/SurfaceView: show() Surface(name=SurfaceView - com.test.rDown/com.test.rDown.MainActivity@7e8d24b@0[21371])/@0x4eecf72 android.view.SurfaceView{7e8d24b VFE...C.. ......ID 753,537-1053,837 #7f08002b app:id/camera_view_sub}
03-28 12:37:03.348 21371-21371/com.test.rDown D/SurfaceView: surfaceCreated 0 #8 android.view.SurfaceView{7e8d24b VFE...C.. ......ID 753,537-1053,837 #7f08002b app:id/camera_view_sub}
    surfaceChanged (300,300) 0 #8 android.view.SurfaceView{7e8d24b VFE...C.. ......ID 753,537-1053,837 #7f08002b app:id/camera_view_sub}
03-28 12:37:03.370 21371-21371/com.test.rDown D/ViewRootImpl@e9581c5[MainActivity]: Relayout returned: old=[0,0][1080,2220] new=[0,0][1080,2220] result=0x3 surface={valid=true 3400005632} changed=false
03-28 12:37:03.375 21371-21371/com.test.rDown V/UVCCameraTextureView: onSurfaceTextureAvailable:android.graphics.SurfaceTexture@bd670be
03-28 12:37:03.376 21371-21371/com.test.rDown V/UVCCameraTextureView: RenderThread#getHandler:
03-28 12:37:03.376 21371-24103/com.test.rDown D/UVCCameraTextureView: RenderThread started
03-28 12:37:03.376 21371-24103/com.test.rDown V/UVCCameraTextureView: RenderThread#init:
03-28 12:37:03.378 21371-24103/com.test.rDown D/EGLBase14: EGLContext created, client version 3
03-28 12:37:03.378 21371-24103/com.test.rDown D/mali_winsys: EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, EGLBoolean) returns 0x3000
03-28 12:37:03.396 21371-21371/com.test.rDown D/ViewRootImpl@e9581c5[MainActivity]: MSG_WINDOW_FOCUS_CHANGED 1 1
03-28 12:37:03.403 21371-21371/com.test.rDown D/InputMethodManager: prepareNavigationBarInfo() DecorView@49a66d6[MainActivity]
    getNavigationBarColor() -855310
03-28 12:37:03.408 21371-21371/com.test.rDown D/InputMethodManager: prepareNavigationBarInfo() DecorView@49a66d6[MainActivity]
03-28 12:37:03.408 21371-21371/com.test.rDown D/InputMethodManager: getNavigationBarColor() -855310
03-28 12:37:03.408 21371-21371/com.test.rDown V/InputMethodManager: Starting input: tba=com.test.rDown ic=null mNaviBarColor -855310 mIsGetNaviBarColorSuccess true , NavVisible : true , NavTrans : false
03-28 12:37:03.408 21371-21371/com.test.rDown D/InputMethodManager: startInputInner - Id : 0
03-28 12:37:03.408 21371-21371/com.test.rDown I/InputMethodManager: startInputInner - mService.startInputOrWindowGainedFocus
03-28 12:37:03.414 21371-21371/com.test.rDown D/InputTransport: Input channel constructed: fd=88
03-28 12:37:03.417 21371-21371/com.test.rDown D/ViewRootImpl@e9581c5[MainActivity]: MSG_RESIZED_REPORT: frame=Rect(0, 0 - 1080, 2220) ci=Rect(0, 72 - 0, 144) vi=Rect(0, 72 - 0, 144) or=1
03-28 12:37:17.282 21371-21371/com.test.rDown V/CameraFragment: onPause:
03-28 12:37:17.331 21371-21371/com.test.rDown D/ViewRootImpl@e9581c5[MainActivity]: MSG_WINDOW_FOCUS_CHANGED 0 1
03-28 12:37:17.331 21371-21371/com.test.rDown D/InputMethodManager: prepareNavigationBarInfo() DecorView@49a66d6[MainActivity]
03-28 12:37:17.331 21371-21371/com.test.rDown D/InputMethodManager: getNavigationBarColor() -855310
03-28 12:37:17.804 21371-21371/com.test.rDown D/InputTransport: Input channel destroyed: fd=88
03-28 12:37:22.383 21371-21371/com.test.rDown D/ViewRootImpl@e9581c5[MainActivity]: MSG_WINDOW_FOCUS_CHANGED 1 1
03-28 12:37:22.397 21371-21371/com.test.rDown D/InputMethodManager: prepareNavigationBarInfo() DecorView@49a66d6[MainActivity]
    getNavigationBarColor() -855310
03-28 12:37:22.401 21371-21371/com.test.rDown D/InputMethodManager: prepareNavigationBarInfo() DecorView@49a66d6[MainActivity]
    getNavigationBarColor() -855310
03-28 12:37:22.401 21371-21371/com.test.rDown V/InputMethodManager: Starting input: tba=com.test.rDown ic=null mNaviBarColor -855310 mIsGetNaviBarColorSuccess true , NavVisible : true , NavTrans : false
03-28 12:37:22.401 21371-21371/com.test.rDown D/InputMethodManager: startInputInner - Id : 0
03-28 12:37:22.401 21371-21371/com.test.rDown I/InputMethodManager: startInputInner - mService.startInputOrWindowGainedFocus
03-28 12:37:22.408 21371-21371/com.test.rDown D/InputTransport: Input channel constructed: fd=88
03-28 12:37:22.430 21371-21371/com.test.rDown D/ViewRootImpl@e9581c5[MainActivity]: setWindowStopped(false) old=false
03-28 12:37:22.483 21371-21371/com.test.rDown V/CameraFragment: onResume:
03-28 12:37:22.483 21371-21371/com.test.rDown V/Connection Step: or this?
03-28 12:37:23.500 21371-24102/com.test.rDown V/Connection Step: this is first?
03-28 12:37:23.500 21371-24102/com.test.rDown V/CameraFragment: OnDeviceConnectListener#onAttach:
03-28 12:37:23.501 21371-24102/com.test.rDown V/CameraFragment: tryOpenUVCCamera:
    openUVCCamera:index=0
03-28 12:37:23.503 21371-24102/com.test.rDown V/CameraClient: Constructor:
03-28 12:37:23.506 21371-24358/com.test.rDown V/CameraClientThread: run:
03-28 12:37:23.507 21371-24102/com.test.rDown V/CameraClient: doBindService:
03-28 12:37:23.522 21371-24102/com.test.rDown V/CameraClient: select:device=/dev/bus/usb/001/002
03-28 12:37:23.524 21371-24102/com.test.rDown V/CameraClient: resize(640,480)
    connect:
03-28 12:37:23.525 21371-24102/com.test.rDown V/Step: One
03-28 12:37:23.526 21371-24358/com.test.rDown V/CameraClientThread: handleSelect:
03-28 12:37:24.196 21371-21371/com.test.rDown V/CameraClient: onServiceConnected:name=ComponentInfo{com.test.rDown/com.test.service.UVCService}
03-28 12:37:24.235 21371-21371/com.test.rDown V/CameraFragment: onPause:
03-28 12:37:24.235 21371-21371/com.test.rDown V/UVCCameraTextureView: getSurface:hasSurface=true
    getPreviewTexture:
03-28 12:37:24.235 21371-24103/com.test.rDown I/UVCCameraTextureView: RenderThread#updatePreviewSurface:
03-28 12:37:24.235 21371-24103/com.test.rDown V/UVCCameraTextureView: updatePreviewSurface:tex_id=1
03-28 12:37:24.236 21371-21371/com.test.rDown V/Preview: am i here?
03-28 12:37:24.236 21371-21371/com.test.rDown V/CameraClient: removeSurface:surface=Surface(name=android.graphics.SurfaceTexture@d336635)/@0xa04daca,hash=168090314
    removeSurface:surface=Surface(name=null)/@0xf6e43b,hash=16180283
03-28 12:37:24.282 21371-24358/com.test.rDown E/CameraClientThread: select:
    android.os.DeadObjectException
        at android.os.BinderProxy.transactNative(Native Method)
        at android.os.BinderProxy.transact(Binder.java:1143)
        at com.test.service.IUVCService$Stub$Proxy.select(IUVCService.java:238)
        at com.test.serviceclient.CameraClient$CameraHandler$CameraTask.handleSelect(CameraClient.java:374)
        at com.test.serviceclient.CameraClient$CameraHandler.handleMessage(CameraClient.java:266)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:214)
        at com.test.serviceclient.CameraClient$CameraHandler$CameraTask.run(CameraClient.java:334)
        at java.lang.Thread.run(Thread.java:764)
03-28 12:37:24.282 21371-24358/com.test.rDown V/CameraClient: handleResize(640,480)
03-28 12:37:24.284 21371-24358/com.test.rDown E/CameraClientThread: handleResize:
    android.os.DeadObjectException
        at android.os.BinderProxy.transactNative(Native Method)
        at android.os.BinderProxy.transact(Binder.java:1143)
        at com.test.service.IUVCService$Stub$Proxy.resize(IUVCService.java:304)
        at com.test.serviceclient.CameraClient$CameraHandler$CameraTask.handleResize(CameraClient.java:485)
        at com.test.serviceclient.CameraClient$CameraHandler.handleMessage(CameraClient.java:291)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:214)
        at com.test.serviceclient.CameraClient$CameraHandler$CameraTask.run(CameraClient.java:334)
        at java.lang.Thread.run(Thread.java:764)
03-28 12:37:24.284 21371-24358/com.test.rDown V/Step: Two
    Three
03-28 12:37:24.284 21371-24358/com.test.rDown V/CameraClientThread: handleConnect:
03-28 12:37:24.284 21371-24358/com.test.rDown V/Step: Four
    Five?
03-28 12:37:24.285 21371-24358/com.test.rDown E/CameraClientThread: handleConnect:
    android.os.DeadObjectException
        at android.os.BinderProxy.transactNative(Native Method)
        at android.os.BinderProxy.transact(Binder.java:1143)
        at com.test.service.IUVCService$Stub$Proxy.connect(IUVCService.java:319)
        at com.test.serviceclient.CameraClient$CameraHandler$CameraTask.handleConnect(CameraClient.java:396)
        at com.test.serviceclient.CameraClient$CameraHandler.handleMessage(CameraClient.java:270)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:214)
        at com.test.serviceclient.CameraClient$CameraHandler$CameraTask.run(CameraClient.java:334)
        at java.lang.Thread.run(Thread.java:764)
03-28 12:37:24.285 21371-24358/com.test.rDown V/CameraClientThread: handleRemoveSurface:surface=Surface(name=android.graphics.SurfaceTexture@d336635)/@0xa04daca,hash=168090314
03-28 12:37:24.286 21371-21371/com.test.rDown D/ViewRootImpl@e9581c5[MainActivity]: MSG_WINDOW_FOCUS_CHANGED 0 1
03-28 12:37:24.286 21371-21371/com.test.rDown D/InputMethodManager: prepareNavigationBarInfo() DecorView@49a66d6[MainActivity]
    getNavigationBarColor() -855310
03-28 12:37:24.286 21371-24358/com.test.rDown E/CameraClientThread: handleRemoveSurface:
    android.os.DeadObjectException
        at android.os.BinderProxy.transactNative(Native Method)
        at android.os.BinderProxy.transact(Binder.java:1143)
        at com.test.service.IUVCService$Stub$Proxy.removeSurface(IUVCService.java:392)
        at com.test.serviceclient.CameraClient$CameraHandler$CameraTask.handleRemoveSurface(CameraClient.java:437)
        at com.test.serviceclient.CameraClient$CameraHandler.handleMessage(CameraClient.java:279)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:214)
        at com.test.serviceclient.CameraClient$CameraHandler$CameraTask.run(CameraClient.java:334)
        at java.lang.Thread.run(Thread.java:764)
03-28 12:37:24.286 21371-24358/com.test.rDown V/CameraClientThread: handleRemoveSurface:surface=Surface(name=null)/@0xf6e43b,hash=16180283
03-28 12:37:24.287 21371-24358/com.test.rDown E/CameraClientThread: handleRemoveSurface:
    android.os.DeadObjectException
        at android.os.BinderProxy.transactNative(Native Method)
        at android.os.BinderProxy.transact(Binder.java:1143)
        at com.test.service.IUVCService$Stub$Proxy.removeSurface(IUVCService.java:392)
        at com.test.serviceclient.CameraClient$CameraHandler$CameraTask.handleRemoveSurface(CameraClient.java:437)
        at com.test.serviceclient.CameraClient$CameraHandler.handleMessage(CameraClient.java:279)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:214)
        at com.test.serviceclient.CameraClient$CameraHandler$CameraTask.run(CameraClient.java:334)
        at java.lang.Thread.run(Thread.java:764)
03-28 12:37:24.288 21371-21371/com.test.rDown V/CameraClient: onServiceDisconnected:name=ComponentInfo{com.test.rDown/com.test.service.UVCService}
03-28 12:37:25.894 21371-21371/com.test.rDown V/CameraClient: onServiceConnected:name=ComponentInfo{com.test.rDown/com.test.service.UVCService}

**Comment by ghost** [comment]
I think I missed something at the initializing. I tried #443 again and it's work now
