### ISSUE TITLE
UsbDeviceConnection.getRawDescriptors()' on a null object reference

### ISSUE THREAD

**Issue by anonym24** [saki4510t/UVCCamera#499]
```
2019-08-06 17:21:24.887 28220-28243/com.serenegiant.usbcameratest0 E/AndroidRuntime: FATAL EXCEPTION: USBMonitor
    Process: com.serenegiant.usbcameratest0, PID: 28220
    java.lang.NullPointerException: Attempt to invoke virtual method 'byte[] android.hardware.usb.UsbDeviceConnection.getRawDescriptors()' on a null object reference
        at com.serenegiant.usb.USBMonitor.updateDeviceInfo(USBMonitor.java:900)
        at com.serenegiant.usb.USBMonitor$UsbControlBlock.<init>(USBMonitor.java:974)
        at com.serenegiant.usb.USBMonitor$UsbControlBlock.<init>(USBMonitor.java:955)
        at com.serenegiant.usb.USBMonitor$3.run(USBMonitor.java:563)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.os.HandlerThread.run(HandlerThread.java:65)

```

Device USB Camera Info: "Corp. USB 2.0 HD Camera, productId: 17688, vendorId:1449"

**Comment by leach-chen** [comment]
I have the same problem，do you have already fix it？
