### ISSUE TITLE
UVC 4k Camera causes black screen on Samsung A31, works on Samsung S10e

### ISSUE THREAD

**Issue by HoekWax** [saki4510t/UVCCamera#597]
Hello,

I have a [4k ELP camera](https://www.amazon.fr/dp/B08CXPZCWB?psc=1) which works well on my S10e, I can see the UVC view on my app using this library, it also works with the samples
Unfortunatly, it doesn't work on the Samsung A31, the screen stays black (in my app and the sample). On the same device, the 4k camera works using CameraFi

Here is some logs printed when the app gets access to the camera and is supposed to show the UVC view, on the A31 (I don't see any errors related to the library) :

```
E/libc: Access denied finding property "vendor.debug.bq.dump"
I/BufferQueueConsumer: [unnamed-25975-2](this:0x74a30be800,id:2,api:0,p:-1,c:25975) setConsumerName: unnamed-25975-2
E/libc: Access denied finding property "vendor.debug.bq.dump"
I/BufferQueueConsumer: [SurfaceTexture-1-25975-2](this:0x74a30be800,id:2,api:0,p:-1,c:25975) setConsumerName: SurfaceTexture-1-25975-2
    [SurfaceTexture-1-25975-2](this:0x74a30be800,id:2,api:0,p:-1,c:25975) setDefaultBufferSize: width=1080 height=607
V/CameraThread: handleOpen:
V/CameraThread: handleClose:
    handleStopRecording:mMuxer=null
V/UVCCameraTextureView: setVideoEncoder:
V/UVCCameraTextureView: RenderThread#setEncoder:encoder=null
I/ReactNativeJS: 'joinRealTimeChannels retry', 1
D/UsbDeviceConnectionJNI: close
I/libusb/core: [27034*core.c:2085:libusb_init2]:libusb v1.0.19.10903
I/libusb/usbfs: [27034*android_usbfs.c:504:op_init2]:start up hotplug event handler
    [27034*android_usbfs.c:512:op_init2]:call android_scan_devices
V/UVCCameraTextureView: getPreviewTexture:
I/UVCCameraTextureView: RenderThread#updatePreviewSurface:
D/UVCCameraTextureView: updatePreviewSurface:release mPreviewSurface
V/UVCCameraTextureView: updatePreviewSurface:tex_id=1
I/BufferQueue: [unnamed-25975-3](this:0x74a30c0000,id:3,api:0,p:-1,c:-1) BufferQueue core=(25975:com.rn.tikaway)
E/libc: Access denied finding property "vendor.debug.bq.dump"
I/BufferQueueConsumer: [unnamed-25975-3](this:0x74a30c0000,id:3,api:0,p:-1,c:25975) connect(C): consumer=(25975:com.rn.tikaway) controlledByApp=true
E/libc: Access denied finding property "vendor.debug.bq.dump"
I/BufferQueueConsumer: [unnamed-25975-3](this:0x74a30c0000,id:3,api:0,p:-1,c:25975) setConsumerName: unnamed-25975-3
E/libc: Access denied finding property "vendor.debug.bq.dump"
I/BufferQueueConsumer: [SurfaceTexture-1-25975-3](this:0x74a30c0000,id:3,api:0,p:-1,c:25975) setConsumerName: SurfaceTexture-1-25975-3
    [SurfaceTexture-1-25975-3](this:0x74a30c0000,id:3,api:0,p:-1,c:25975) setDefaultBufferSize: width=1080 height=607
V/UVCCameraTextureView: getPreviewTexture:
I/UVCCameraTextureView: RenderThread#updatePreviewSurface:
D/UVCCameraTextureView: updatePreviewSurface:release mPreviewSurface
V/UVCCameraTextureView: updatePreviewSurface:tex_id=1
I/BufferQueue: [unnamed-25975-4](this:0x74a30c1800,id:4,api:0,p:-1,c:-1) BufferQueue core=(25975:com.rn.tikaway)
E/libc: Access denied finding property "vendor.debug.bq.dump"
I/BufferQueueConsumer: [unnamed-25975-4](this:0x74a30c1800,id:4,api:0,p:-1,c:25975) connect(C): consumer=(25975:com.rn.tikaway) controlledByApp=true
E/libc: Access denied finding property "vendor.debug.bq.dump"
I/BufferQueueConsumer: [unnamed-25975-4](this:0x74a30c1800,id:4,api:0,p:-1,c:25975) setConsumerName: unnamed-25975-4
E/libc: Access denied finding property "vendor.debug.bq.dump"
I/BufferQueueConsumer: [SurfaceTexture-1-25975-4](this:0x74a30c1800,id:4,api:0,p:-1,c:25975) setConsumerName: SurfaceTexture-1-25975-4
    [SurfaceTexture-1-25975-4](this:0x74a30c1800,id:4,api:0,p:-1,c:25975) setDefaultBufferSize: width=1080 height=607
I/AbsUVCCameraHandler: supportedSize:{"formats":[{"index":1,"type":6,"default":1,"size":["3840x2160","1920x1080","1280x720","2592x1944","2048x1536","1600x1200","1280x960","1024x768","800x600","640x480","320x240","3840x2880","3264x2448"]},{"index":2,"type":4,"default":1,"size":["3840x2160","1920x1080","1280x720","2592x1944","2048x1536","1600x1200","1280x960","1024x768","800x600","640x480","320x240","3840x2880","3264x2448"]}]}
V/CameraThread: handleStartPreview:
D/AbsUVCCameraHandler: AbstractUVCCameraHandler, handleStartPreview: pour changer la QUALITE de la vue UVC 
I/chatty: uid=10259(com.rn.tikaway) CameraThread identical 4 lines
D/AbsUVCCameraHandler: AbstractUVCCameraHandler, handleStartPreview: pour changer la QUALITE de la vue UVC 
D/Surface: Surface::setBuffersUserDimensions(this=0x6b5f590000,w=640,h=480)
I/libUVCCamera: [27045*UVCPreview.cpp:492:prepare_preview]:frameSize=(1280,720)@MJPEG
D/Surface: Surface::setBuffersUserDimensions(this=0x6b5f590000,w=1280,h=720)
I/libUVCCamera: [27047*UVCPreview.cpp:258:callbackPixelFormatChanged]:PIXEL_FORMAT_RAW:
W/libUVCCamera: [27046*UVCPreview.cpp:119:get_frame]:allocate new frame
W/libUVCCamera: [27045*UVCPreview.cpp:119:get_frame]:allocate new frame
W/ConnectionTracker: Exception thrown while unbinding
    java.lang.IllegalArgumentException: Service not registered: ls@5b758e4
        at android.app.LoadedApk.forgetServiceDispatcher(LoadedApk.java:1870)
        at android.app.ContextImpl.unbindService(ContextImpl.java:1848)
        at android.content.ContextWrapper.unbindService(ContextWrapper.java:755)
        at ci.f(:com.google.android.gms.dynamite_measurementdynamite@204714081@20.47.14 (120400-0):1)
```

Do you guys have any idea if there is a fix available ?

Thanks.

**Comment by bandrarom** [comment]
how did you connect uvc camera with agora.did you  use mCameraHelper.setOnPreviewFrameListener(new AbstractUVCCameraHandler.OnPreViewResultListener() ?
