### ISSUE TITLE
java.lang.UnsupportedOperationException: open failed:result=-50 at com.serenegiant.usb.UVCCamera.open(UVCCamera.java:204)

### ISSUE THREAD

**Issue by HM-Houda** [saki4510t/UVCCamera#622]
Hello every one,
I encounter this error often. and I failed to resolve it.
I found on the net that it is necessary to have an NDK 14b in order to solve this but it does not work for me.

Any idea or proposal is welcome.
Thank you.

**Comment by flexnguyenluu** [comment]
Hi, could you resolve this ? I encounter this too.

**Comment by HM-Houda** [comment]
Hello, Sorry I didn't because I change the project.
However I suggest you to see this git project https://github.com/jiangdongguo/AndroidUSBCamera.
And to jungle with the different kind of H264/AAC/YUV/PCM .
Hopping this help you.HM-Houda

-------- Message original --------
Sujet: Re: [saki4510t/UVCCamera] java.lang.UnsupportedOperationException: open failed:result=-50 at com.serenegiant.usb.UVCCamera.open(UVCCamera.java:204) (#622)
Date: Lundi, Février 05, 2024 10:21 CET
De: nguyenluu1998 ***@***.***>
Répondre à: saki4510t/UVCCamera ***@***.***>

Pour: saki4510t/UVCCamera ***@***.***>
Copie: HM-Houda ***@***.***>, Author ***@***.***>

Références: 




 
 
Hi, could you resolve this ? I encounter this too.
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID: ***@***.***> [ { ***@***.***": "http://schema.org", ***@***.***": "EmailMessage", "potentialAction": { ***@***.***": "ViewAction", "target": "https://github.com/saki4510t/UVCCamera/issues/622#issuecomment-1926540163", "url": "https://github.com/saki4510t/UVCCamera/issues/622#issuecomment-1926540163", "name": "View Issue" }, "description": "View this Issue on GitHub", "publisher": { ***@***.***": "Organization", "name": "GitHub", "url": "https://github.com" } } ]***>

-- 
Houda MAAMATOU |Ingénieure R&D
LOGIROAD
5, rue de l’Enclose
44118 La Chevrolière
***@***.***
Tel: +337 81 53 25 77 / +216 28 666712
vidéo

**Comment by flexnguyenluu** [comment]
Hi, thanks for the reply.
For anyone who looking for the solution, I was able to fix this. In my case, it's related to ndk.dir in local.properties. Set ndk.dir point to the `android-ndk-r14b` ndk directory.
Download at: https://github.com/android/ndk/wiki/Unsupported-Downloads
